version: '3.4'
services:
    db:
        container_name: mysql
        image: mysql:latest
        restart: always
        ports:
          - 3306:3306
        environment:
          - MYSQL_DATABASE=db
          - MYSQL_ROOT_PASSWORD=<password>
        networks:
            - bezkie
    bezkie.api:
        image: ${DOCKER_REGISTRY-}bezkieapi
        restart: always
        build:
            context: .
            dockerfile: bezkie.api/Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - db
        networks:
            - bezkie
  
networks:
  bezkie:
    driver: bridge